import { Session } from '@/src/types/session';

export function createEmptySession(): Session {
  return {
    id: Date.now(),
    date: new Date().toISOString().split("T")[0],
    duration: "60",
    environment: 0 || 1,
    fatigue: null,
    fun: null,
    successType: null,
    successDomain: null,
    successDescription: "",
    difficultyType: null,
    difficultyDomain: null,
    difficultyDescription: "",
    notes: "",
    oppositionLevel: null,
    confidence: null,
  };
}

export const mockSessions: Session[] = [
  {
    id: 0,
    date: "2025-10-28",
    duration: "60",
    environment: 1,
    fatigue: 4,
    fun: 5,
    successType: 2,
    successDomain: 1,
    successDescription: "Great takedown defense and quick transitions.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Struggled with guard passing against heavier opponents.",
    notes: "Felt strong today, but need to work on breathing under pressure.",
    oppositionLevel: 3,
    confidence: 4,
  },
  {
    id: 1,
    date: "2025-10-26",
    duration: "45",
    environment: 0,
    fatigue: 2,
    fun: 4,
    successType: 0,
    successDomain: 0,
    successDescription: "Perfect technique execution during drills.",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Need to work on tactical positioning.",
    notes: "Great focus session, technique feels more natural.",
    oppositionLevel: null,
    confidence: 3,
  },
  {
    id: 2,
    date: "2025-10-25",
    duration: "75",
    environment: 1,
    fatigue: 5,
    fun: 3,
    successType: 1,
    successDomain: 1,
    successDescription: "Good reaction time in sparring.",
    difficultyType: 1,
    difficultyDomain: 1,
    difficultyDescription: "Tactical decisions under pressure were challenging.",
    notes: "Exhausting session but learned a lot about endurance.",
    oppositionLevel: 2,
    confidence: 3,
  },
  {
    id: 3,
    date: "2025-10-20",
    duration: "30",
    environment: 0,
    fatigue: 1,
    fun: 5,
    successType: 0,
    successDomain: 0,
    successDescription: "Smooth technique flow during practice.",
    difficultyType: 0,
    difficultyDomain: 0,
    difficultyDescription: "Minor issues with footwork timing.",
    notes: "Short but effective practice session.",
    oppositionLevel: null,
    confidence: 5,
  },
  {
    id: 4,
    date: "2025-10-21",
    duration: "60",
    environment: 1,
    fatigue: 3,
    fun: 4,
    successType: 1,
    successDomain: 0,
    successDescription: "Great group drilling session.",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Tactical understanding needs improvement.",
    notes: "Good team chemistry during practice.",
    oppositionLevel: 1,
    confidence: 4,
  },
  {
    id: 5,
    date: "2025-10-22",
    duration: "50",
    environment: 1,
    fatigue: 2,
    fun: 4,
    successType: 2,
    successDomain: 1,
    successDescription: "Improved control over sparring partner.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Hard time with escapes from mount.",
    notes: "Focus on mount escapes next time.",
    oppositionLevel: 2,
    confidence: 3,
  },
  {
    id: 6,
    date: "2025-10-21",
    duration: "40",
    environment: 0,
    fatigue: 3,
    fun: 3,
    successType: 1,
    successDomain: 0,
    successDescription: "Great flow in solo drills.",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Struggled maintaining pace towards end.",
    notes: "Work on endurance for longer drills.",
    oppositionLevel: null,
    confidence: 4,
  },
  {
    id: 7,
    date: "2025-10-20",
    duration: "70",
    environment: 1,
    fatigue: 5,
    fun: 2,
    successType: 0,
    successDomain: 1,
    successDescription: "Good transitions under pressure.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Opponent used strong grips, difficult to break.",
    notes: "Practice more grip fighting techniques.",
    oppositionLevel: 3,
    confidence: 2,
  },
  {
    id: 8,
    date: "2025-10-19",
    duration: "60",
    environment: 0,
    fatigue: 1,
    fun: 5,
    successType: 2,
    successDomain: 0,
    successDescription: "Excellent movement in positional drilling.",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Focus faded near the end.",
    notes: "Try shorter, high-intensity sessions.",
    oppositionLevel: null,
    confidence: 5,
  },
  {
    id: 9,
    date: "2025-10-18",
    duration: "80",
    environment: 1,
    fatigue: 4,
    fun: 4,
    successType: 1,
    successDomain: 1,
    successDescription: "Maintained composure during live rounds.",
    difficultyType: 1,
    difficultyDomain: 1,
    difficultyDescription: "Found it hard to keep base when tired.",
    notes: "More balance drills needed.",
    oppositionLevel: 2,
    confidence: 3,
  },
  {
    id: 10,
    date: "2025-10-26",
    duration: "50",
    environment: 0,
    fatigue: 2,
    fun: 3,
    successType: 0,
    successDomain: 0,
    successDescription: "Nice entries and footwork in warmup.",
    difficultyType: 0,
    difficultyDomain: 0,
    difficultyDescription: "Some mistakes in basic combinations.",
    notes: "Review fundamentals before next session.",
    oppositionLevel: null,
    confidence: 4,
  },
  {
    id: 11,
    date: "2025-10-16",
    duration: "60",
    environment: 1,
    fatigue: 5,
    fun: 2,
    successType: 1,
    successDomain: 0,
    successDescription: "Held own against higher belts.",
    difficultyType: 1,
    difficultyDomain: 1,
    difficultyDescription: "Cardio faded after first two rounds.",
    notes: "Start running twice a week.",
    oppositionLevel: 3,
    confidence: 2,
  },
  {
    id: 12,
    date: "2025-10-15",
    duration: "65",
    environment: 0,
    fatigue: 3,
    fun: 4,
    successType: 2,
    successDomain: 1,
    successDescription: "Felt present and focused throughout.",
    difficultyType: 0,
    difficultyDomain: 0,
    difficultyDescription: "Still rushing transitions.",
    notes: "Slow down and focus on each position.",
    oppositionLevel: null,
    confidence: 3,
  },
  {
    id: 13,
    date: "2025-10-14",
    duration: "75",
    environment: 1,
    fatigue: 3,
    fun: 5,
    successType: 1,
    successDomain: 0,
    successDescription: "Sharp submissions in group sparring.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Gassed after first five minutes.",
    notes: "Work on pacing during live rolling.",
    oppositionLevel: 2,
    confidence: 4,
  },
  {
    id: 14,
    date: "2025-10-13",
    duration: "30",
    environment: 0,
    fatigue: 1,
    fun: 4,
    successType: 0,
    successDomain: 1,
    successDescription: "Accurate takedown entries.",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Balance issues on one side.",
    notes: "Drill both sides equally.",
    oppositionLevel: null,
    confidence: 5,
  },
  {
    id: 15,
    date: "2025-10-12",
    duration: "60",
    environment: 1,
    fatigue: 4,
    fun: 2,
    successType: 2,
    successDomain: 1,
    successDescription: "Stayed calm despite mistakes.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Opponent overpowered in most scrambles.",
    notes: "Work strength with new partner.",
    oppositionLevel: 1,
    confidence: 2,
  },
  {
    id: 16,
    date: "2025-10-11",
    duration: "90",
    environment: 0,
    fatigue: 3,
    fun: 5,
    successType: 1,
    successDomain: 0,
    successDescription: "Best practice so far!",
    difficultyType: 0,
    difficultyDomain: 1,
    difficultyDescription: "Timing still off on armbars.",
    notes: "Do more reps on the armbar setup.",
    oppositionLevel: null,
    confidence: 4,
  },
  {
    id: 17,
    date: "2025-10-10",
    duration: "60",
    environment: 1,
    fatigue: 5,
    fun: 1,
    successType: 1,
    successDomain: 1,
    successDescription: "Defended well even under fatigue.",
    difficultyType: 1,
    difficultyDomain: 1,
    difficultyDescription: "Lost position after failed pass.",
    notes: "Relax at failed attempts.",
    oppositionLevel: 3,
    confidence: 3,
  },
  {
    id: 18,
    date: "2025-10-09",
    duration: "45",
    environment: 0,
    fatigue: 2,
    fun: 3,
    successType: 0,
    successDomain: 0,
    successDescription: "Nice recovery in last round.",
    difficultyType: 0,
    difficultyDomain: 0,
    difficultyDescription: "Off-balance on sprawls.",
    notes: "Practice basic sprawls at home.",
    oppositionLevel: null,
    confidence: 3,
  },
  {
    id: 19,
    date: "2025-10-08",
    duration: "50",
    environment: 1,
    fatigue: 3,
    fun: 5,
    successType: 2,
    successDomain: 0,
    successDescription: "Team encouraged my efforts.",
    difficultyType: 1,
    difficultyDomain: 0,
    difficultyDescription: "Mentally checked out halfway through.",
    notes: "Focus on mental stamina.",
    oppositionLevel: 2,
    confidence: 5,
  },
];
